# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMn4t9TtX_BhdwpbUn476LtZqOh2hnql

M512A Data Visualisation and Communication

Name: Poojitha Kore(GH1044246)

Tutor: Prof.William Baker Morrison

**Title:**

“Understanding Workplace Mental Health and Its Impact on Productivity

#1. Introduction

Mental health has become an increasingly important factor in workplace performance, particularly in high-pressure industries such as technology. Employees experiencing mental health challenges may face reduced productivity, increased absenteeism, and lower job satisfaction.

This analysis aims to explore patterns in employee mental health using survey data from the technology sector. The objective is to identify key risk factors, understand behavioral patterns in seeking treatment, and provide insights that can support better organizational decision-making.

**Audience:**

 HR managers, business leaders, and policy makers in technology companies.

 * The primary audience for this analysis includes human resource managers, organizational leaders, and policymakers who are interested in improving employee well-being and productivity.



**Purpose:**
* Mental health significantly affects employee well-being and productivity, yet many issues remain hidden, particularly in high-pressure tech environments.
* This analysis aims to uncover patterns of mental health challenges, identify hidden high-risk employees, and provide actionable insights for company leadership to design targeted interventions.

**Objective**

* The objective of this analysis is to explore patterns, relationships, and key drivers of mental health issues among employees.
*  By applying effective data visualization techniques, this project aims to provide actionable insights that can help organizations create a healthier and more productive work environment.

**Business Relevance
Mental health directly impacts:**
- Productivity
- Employee retention
- Workplace culture

Using data visualization, this analysis transforms raw survey data into clear insights that support better decision-making.

# Use of Data:

Data helps us understand demographics, work interference patterns, treatment-seeking behaviors, and company policy effectiveness.
Insights can guide HR policies, wellness programs, and targeted mental health initiatives.

# Data Source:

Dataset: “Mental Health in Tech Survey”

URL: https://www.kaggle.com/osmi/mental-health-in-tech-survey

Description:

 * The dataset contains 1,259 rows and 27 columns. Each row represents an individual survey response, while each column captures demographic, workplace, or mental health-related information.

Important Columns Include:
* Age → Employee age
* Gender → Gender of respondent
* treatment → Whether the employee sought mental health treatment
* work_interfere → How mental health affects work
* benefits → Availability of mental health benefits
* seek_help → Whether employer provides help resources
* remote_work → Work mode
* family_history → History of mental illness

These variables allow us to analyze both individual risk factors and organizational influence.

#2.DATA LOADING and DATA EXPLORATION
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("survey.csv")
df.head()

df.shape

"""The dataset contains 1,259 rows and 27 columns, representing individual responses collected through a global survey.

Each row corresponds to a single employee, while each column captures information related to:

* Demographics (age, gender, country)
* Workplace conditions (remote work, company size, benefits)
* Mental health indicators (treatment, work interference, family history)

This structure enables analysis of both individual-level behavior and organizational influence on mental health outcomes.
"""

df.columns

"""The dataset is a mix of categorical and numerical variables."""

df.info()

"""This reveals that most variables are categorical, while a few (like age) are numerical. It also highlights missing values in several columns."""

df.describe()

df.isnull().sum()

"""Certain variables such as State, Self_employed contain missing values. These are important because they relate directly to mental health impact and cannot be ignored.

Check for duplicates
"""

df.duplicated().sum()

"""Duplicate entries, if present, may distort results and must be removed

Key Observations:
- Missing values are present in several columns
- Some columns contain inconsistent or sparse responses
- Duplicate entries are absent

### Data Quality Issues:
- Missing values in key fields
- Potential inconsistencies in categorical responses

#3. DATA CLEANING and PREPROCESSING

Remove duplicates if any
"""

df = df.drop_duplicates()
print(f"New shape after removing duplicates: {df.shape}")

"""No duplicates are found.

Handle Age Outliers
"""

df = df[(df['Age'] > 0) & (df['Age'] < 100)]

"""Handle Missing values

Missing values exist in state, self_employed, and comments.
"""

num_cols = df.select_dtypes(include='number').columns
print("Numerical columns:", list(num_cols))

"""Median is used for numerical data to avoid influence of outliers"""

# Categorical columns
cat_cols = df.select_dtypes(include='object').columns
print("Categorical columns:", list(cat_cols))

"""Mode is used for categorical variables to preserve most common responses

Handle missing values

Numerical columns
"""

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

"""Numerical columns (like age) were filled with the median value to maintain central tendencies"""

for col in cat_cols:
    df[col] = df[col].fillna('Unknown')

"""Categorical columns (like gender, state, self_employed) were filled with "Unknown" to preserve all rows while clearly marking missing information.

**Clean Gender**

The Gender variable contains inconsistent and non-standard entries, including variations such as “Male”, “M”, “male”, “Female”, “F”, as well as non-binary or ambiguous values like “trans” and “non-binary”. These inconsistencies result in fragmented categories and can produce misleading visualizations. To ensure accurate analysis, the data was cleaned and standardized into consistent groups.
"""

def clean_gender(g):
    g = str(g).lower().strip()

    if g in ['male', 'm']:
        return 'Male'
    elif g in ['female', 'f']:
        return 'Female'
    else:
        return 'Other'

df['Gender_Clean'] = df['Gender'].apply(clean_gender)

"""The Gender column contained inconsistent and noisy labels (e.g., "Male", "M", "male", as well as non-standard entries such as "trans" and "non-binary"). These were consolidated into three categories ("Male", "Female", and "Other") to ensure meaningful grouping and avoid misleading visualizations."""

print("Missing values after cleaning:")
print(df.isnull().sum())

"""The dataset no longer contains any missing values in the columns that will be used for analysis.
All numerical and categorical columns will now have 0 missing values.
 This ensures that all subsequent visualizations and insights are stable, reproducible, and reliable.

**Data Cleaning & Preprocessing**

### Steps Taken:

1. Removed duplicate records to ensure data consistency and avoid repeated observations influencing the analysis.
2. Handled missing values:
* Numerical variables such as Age were filled using the median to reduce the impact of outliers.
* Categorical variables (e.g., work_interfere, benefits) were filled using the mode to preserve the most frequent responses.
3. Standardized categorical variables:
The Gender column contained inconsistent and non-standard entries such as “Male”, “M”, “male”, “Female”, “F”, as well as values like “trans”, “non-binary”, and “male-ish”. These were cleaned and grouped into consistent categories (Male, Female, and Other) to ensure meaningful analysis and avoid fragmented visualizations.

### Reasoning:
1. The median was used for numerical data as it is robust to outliers and better represents central tendency in skewed distributions.
2. The mode was used for categorical variables to maintain the most representative category without introducing artificial bias.
3. Removing duplicates ensures that each observation contributes equally to the analysis.
4. Standardizing categorical variables improves data quality and prevents misleading visualizations caused by inconsistent labels.

After preprocessing, the dataset is cleaned, consistent, and suitable for reliable analysis. These steps ensure that the resulting visualizations are accurate, interpretable, and aligned with the business context.

#4. Feature Engineering
"""

df['high_risk'] = (
    (df['work_interfere'].isin(['Often','Sometimes'])) &
    (df['treatment'] == 'No')
)

"""In this analysis, a new variable called high_risk was created by combining work interference and treatment status. This allows the identification of employees who are experiencing mental health challenges but are not seeking support. Such a feature provides deeper business value by highlighting hidden risk groups that would not be directly observable from individual variables.

#5.Explanatory Data Visualisation

# **Insight 1: Workforce Dominated by Employees in Prime Productivity Years**

**Business Importance:**

Understanding the age distribution of employees helps organizations assess workforce composition, productivity potential, and long-term talent planning. A workforce concentrated in mid-career stages often indicates strong productivity but may lack senior experience and mentorship.
"""

plt.figure(figsize=(8,6))
plt.hist(df['Age'], bins=20, color='#69b3a2', edgecolor='black')
plt.title("Age Distribution of Employees", fontsize=14)
plt.xlabel("Age", fontsize=12)
plt.ylabel("Number of Employees", fontsize=12)
plt.show()

"""A histogram was created using plt.hist() to display the distribution of employee ages. The data was divided into 20 bins to provide sufficient granularity while maintaining readability. This allows clear identification of where employee ages are most concentrated.

**Design Decisions**

* Understand context: Analyze workforce age distribution
* A histogram is used to show the frequency of age groups clearly.
* The bin structure helps identify where employees are concentrated, and the simple design avoids clutter.
* Draw attention: Bin structure highlights peak age ranges
* Clear axis labels and readable scale
* This chart Reveals a story that concentration of employees in specific age groups

**Insight & Interpretation**

The majority of employees fall between 25 and 40 years old, with the highest concentration around 30–35 years. There are relatively few employees below 22 and above 50, indicating underrepresentation at both early-career and senior levels.

**Business Recommendation**
* Focus on retention and career development for mid-career employees
* Introduce mentorship programs to compensate for fewer senior employees
* Improve hiring strategies to balance junior and senior talent pipelines

# **Insight 2: Gender Gaps in Mental health Treatment Seeking Behavior**

**Business Importance:**

Understanding gender differences in treatment-seeking behavior is critical for designing inclusive mental health strategies. If certain groups are less likely to access support, organizations risk leaving vulnerable employees untreated, which can negatively impact productivity, engagement, and retention.
"""

plt.figure(figsize=(7,5))

sns.countplot(
    x='Gender_Clean',
    hue='treatment',
    data=df,
    palette=['#4CAF50', '#F44336']
)

plt.title("Mental Health Treatment by Gender", fontsize=14)
plt.xlabel("Gender")
plt.ylabel("Number of Employees")

plt.tight_layout()
plt.show()

"""A grouped bar chart was created using sns.countplot() to compare treatment-seeking behavior across gender categories. Prior to visualization, the Gender variable was cleaned and standardized into three categories: Male, Female, and Other, to remove inconsistencies and ensure accurate grouping. The hue parameter was used to distinguish between employees who sought treatment and those who did not.

* Green = treatment
* Red = no treatment

**Design Decisions**

* The context was to compare treatment behavior across genders.
* A grouped bar chart was chosen as it enables clear side-by-side comparison within each category.
* Clutter was minimized through a simple and structured layout.
* The use of contrasting colors for “Yes” and “No” effectively separates responses, while the taller “No” bar for males immediately draws attention, making it the focal point of the visualization.
* The design ensures clarity while emphasizing the imbalance.


This chart tells a compelling story access to mental health support alone is not sufficient. The key takeaway is that organizations must also address stigma, awareness, and psychological safety—particularly among male employees—to ensure that available resources are actively utilized and effective.

**Insight & Interpretation**

Among female employees, approximately 165 individuals sought treatment, compared to around 70 who did not, indicating a strong tendency toward seeking help.

In contrast, among male employees, approximately 440 sought treatment, while a larger group of about 530 did not, showing a clear reluctance.

This reveals:

Females have a higher treatment adoption rate,
Males show a higher avoidance rate, despite being the majority

**Business Recommendation**
* Develop targeted awareness campaigns for male employees
* Reduce stigma through leadership nd communication
* Provide confidential and anonymous support options

# **Insight 3: Mental Health Challenges Actively Impacting Employee Performance**

**Business Importance:**

Understanding how frequently mental health interferes with work helps organizations assess the scale of the problem. This insight allows companies to prioritize interventions and allocate resources effectively.
"""

plt.figure(figsize=(8,5))
sns.countplot(x='work_interfere', data=df, hue='work_interfere',
              palette='muted', order=['Never','Rarely','Sometimes','Often'],
              legend=False)
plt.title("Work Interference Due to Mental Health", fontsize=14)
plt.xlabel("Interference Level", fontsize=12)
plt.ylabel("Number of Employees", fontsize=12)
plt.show()

"""The visualization was created using sns.countplot() to display the frequency of each category in the work_interfere variable.
 The categories were explicitly ordered as Never, Rarely, Sometimes, Often to maintain logical progression.

 The chart counts the number of employees in each category, making it easy to compare how often mental health impacts work.

**Design Decisions**
* The context was to analyze the frequency of work interference due to mental health.
* A bar chart was selected as it effectively compares categorical distributions.
* Clutter was minimized through a clean and simple layout.
* The ordered categories (Never → Often) establish a logical progression of severity, while the height of the “Sometimes” bar naturally draws attention.
* Distinct colors further enhance clarity without overwhelming the viewer.


This chart tells a compelling story: mental health interference is not extreme for most employees, but it is persistent. The key takeaway is that organizations should focus not only on employees experiencing frequent challenges but also on those in the “Sometimes” category, as they represent the largest and most impactful group in terms of overall workforce performance.

**Insight & Interpretation**
The majority of employees report that mental health “Sometimes” interferes with their work (approximately 450–470 employees). This is significantly higher than those who report “Never” (~210)

 “Rarely” (~170),

 or “Often” (~140).

This indicates that:

* Mental health challenges are widespread, not isolated
* Most employees experience occasional disruption, rather than constant or no impact

**Business Recommendation**
* Focus on preventive mental health strategies, not just crisis support
* Introduce regular wellness check-ins and flexible work policies
* Provide resources that help employees manage moderate, recurring stress

# **Insight 4: Company-Provided Benefits Drive Higher Treatment Adoption**

**Business Importance:**

Evaluating the relationship between company benefits and treatment-seeking behavior helps organizations measure the effectiveness of workplace mental health policies.
"""

plt.figure(figsize=(8,5))
sns.countplot(x='benefits', hue='treatment', data=df, palette='Set2')
plt.title("Company Benefits vs Treatment Seeking", fontsize=14)
plt.xlabel("Benefits Available", fontsize=12)
plt.ylabel("Number of Employees", fontsize=12)
plt.show()

"""A grouped bar chart using sns.countplot() compares treatment behavior across three categories: Yes (benefits available), No, and Don’t Know. The hue represents whether employees sought treatment.


**Design Decisions**
* Analyze impact of benefits on behavior
* A grouped bar chart clearly compares treatment behavior across benefit categories.
* The layout and colors make it easy to interpret differences.
* Draw attention: Differences between categories are visually distinct
* Logical grouping enhances clarity
* This chart tells a story that companies should not only provide benefits but also ensure employees are aware of them to improve well-being.


**Insight & Interpretation**
* When benefits are available(Yes): ~300 employees sought treatment vs ~170 who did not
* When unaware(Don't know): ~260 did not seek treatment vs ~150 who did
* When no benefits exist(No) nearly balanced (~180 yes vs 190 no)

 This shows:

* Availability increases treatment adoption
* Lack of awareness significantly reduces usage

**Business Recommendation**
* Improve communication of benefits
* Ensure employees clearly understand available support
* Regularly promote mental health programs

# **Insight 5: Remote Work slightly encourages Mental Health Treatment Seeking**

**Business Importance:**

Work environment plays a role in mental health engagement. Understanding this helps organizations design flexible policies.
"""

plt.figure(figsize=(7,5))
sns.countplot(x='remote_work', hue='treatment', data=df, palette='cool')
plt.title("Remote Work vs Mental Health Treatment", fontsize=14)
plt.xlabel("Remote Work", fontsize=12)
plt.ylabel("Count", fontsize=12)
plt.show()

"""A grouped bar chart compares treatment-seeking behavior between remote and non-remote employees using sns.countplot().



**Design Decisions**
* A grouped bar chart is used to compare two categories effectively. * * The side-by-side bars and color contrast make differences easy to understand.


This chart tells a story that flexible work environments can play a role in encouraging employees to seek mental health support.

**Insight & Interpretation**
* Non-remote employees: roughly equal split (~430–440 each) between treatment and no treatment
* Remote employees: about 200 sought treatment vs ~180 who did not

This indicates:

* Remote workers show a slightly higher tendency to seek treatment
* Non-remote workers may face barriers such as time or stigma

**Business Recommendation**
* Promote flexible work policies
* Provide virtual mental health support
* Reduce workplace stigma in office environments

# **Insight 6: A Hidden Segment of High-Risk Employees Avoiding Treatment**

**Business Importance:**

Identifying high-risk employees who may not seek help is critical for preventing burnout and productivity loss.
"""

plt.figure(figsize=(10,4))

# Separate employees by risk status
high_risk = df[df['high_risk'] == True]
normal_risk = df[df['high_risk'] == False]

# Plot normal employees
plt.scatter(normal_risk['Age'], [1]*len(normal_risk),
            alpha=0.3, label='Normal Risk', color='blue')

# Plot high-risk employees
plt.scatter(high_risk['Age'], [1]*len(high_risk),
            color='red', label='High Risk', alpha=0.8)

# Labels and title
plt.xlabel("Age of Employees", fontsize=12)
plt.ylabel("Employee Risk Indicator", fontsize=12)
plt.yticks([])  # Y-axis is categorical (all points on same line)
plt.title("Hidden High-Risk Employees Highlighted", fontsize=14)

#legend
plt.legend()
plt.show()

"""A scatter plot was used to visualize individual employees by age, distinguishing high-risk and normal-risk groups using color coding.
From a business perspective, this group represents a critical workforce segment whose performance may be affected.


**Design Decisions**
* The context was to identify risk distribution by age.
* A scatter plot was used for individual-level clarity.
* Clutter was minimized with a simple layout.
* Red color draws attention to high-risk employees.

* This chart tells a story that risk is not evenly distributed across ages. Organizations should focus on proactive support for the 20–45 age group to prevent hidden productivity losses and ensure workforce well-being.

**Insight & Interpretation**

High-risk employees are primarily concentrated between ages 20 and 45, with the densest clustering between 25 and 40. Employees above 50 are mostly in the normal-risk category, with very few high-risk cases.

This suggests:

* Risk is concentrated in core working-age employees
* A significant portion of the workforce may be silently struggling

**Business Recommendation**
* Implement early detection and intervention programs
* Provide targeted support for employees aged 20–45
* Encourage proactive mental health check-ins

# **Insight 7: Work Interference varies significantly across Age Groups**

**Business Importance:**

This analysis helps determine whether certain age groups are more affected by mental health challenges, allowing organizations to design age-specific or universal interventions.
"""

plt.figure(figsize=(8,5))
sns.boxplot(x='work_interfere', y='Age', data=df, palette='pastel', order=['Never','Rarely','Sometimes','Often'], legend=False)
plt.title("Age Distribution by Work Interference Level", fontsize=14)
plt.xlabel("Work Interference", fontsize=12)
plt.ylabel("Age", fontsize=12)
plt.show()

"""A boxplot was created using sns.boxplot() to compare the distribution of age across different levels of work interference. The x-axis represents interference categories, while the y-axis shows age. The boxplot displays the median, interquartile range, and outliers for each group.

**Design Decisions**
* Compare age distribution across interference levels
*  Boxplot to show spread, median, and outliers
* Clutter was reduced by grouping categories cleanly without unnecessary elements.
* Attention is drawn to the spread and median lines, helping identify subtle differences.
* The design uses soft, consistent colors to maintain clarity.
* This chart tells the story that mental health interference is consistent across ages. Organizations cannot assume only certain age groups are at risk and should implement inclusive mental health strategies for all employees


**Insight & Interpretation:**

The median age across all categories is very similar, generally around 30–32 years old. The interquartile ranges (middle 50%) also overlap significantly across all groups.

* “Never”: Median ~31
* “Rarely”: Median ~32
* “Sometimes”: Median ~32
* “Often”: Median ~30

Additionally, all categories show a similar age spread (roughly mid-20s to late-30s) with some outliers above 50.

This indicates:

* Mental health interference is not strongly dependent on age
* Employees across all age groups experience similar levels of impact

**Business Recommendation:**

* Avoid assuming mental health issues are limited to younger or older employees
* Implement company-wide mental health programs
* Ensure support systems are accessible to employees of all age groups

Employees reporting "Often" interference tend to be slightly younger. HR may need to focus on early-career stress management programs.

# **Insight 8 : Mid-Career Employees experience Higher Work Interference on Average**

**Business Importance:**

Understanding how mental health interference varies with age helps determine whether interventions should be targeted or universal.
"""

interf_map = {'Never':0, 'Rarely':1, 'Sometimes':2, 'Often':3}
df['work_interfere_num'] = df['work_interfere'].map(interf_map)

avg_interf_by_age = df.groupby('Age')['work_interfere_num'].mean().reset_index()

# Plot line chart
plt.figure(figsize=(10,5))
plt.plot(avg_interf_by_age['Age'], avg_interf_by_age['work_interfere_num'],
         color='green', marker='o')
plt.xlabel("Age of Employees", fontsize=12)
plt.ylabel("Average Work Interference Score", fontsize=12)
plt.title("Average Work Interference by Age", fontsize=14)
plt.grid(True)
plt.show()

"""A line chart was created by converting categorical interference levels into numeric values and calculating the average interference score for each age group.

**Design Decision**
* The context was to analyze trends over age, making a line chart the best choice for showing continuous progression.
* Clutter was minimized by using a single line with clear markers. Attention is naturally drawn to peaks and dips in the trend.
* The design ensures smooth readability and logical flow across ages.

This chart tells a compelling story that mental health interference is steady across most ages, highlighting the importance of sustained organizational support.

**Insight & Interpretation**

Most employees between ages 25 and 45 show average interference scores between 1.3 and 1.8, indicating moderate impact. Occasional peaks appear around 45–50 and near 60, reaching closer to 2.0–3.0, though these may be influenced by smaller sample sizes.

This indicates:

* Mental health interference is consistent across most age groups
* It is a persistent issue, not limited to specific ages

**Business Recommendation**
* Implement continuous mental health support systems
* Avoid focusing only on specific age groups
* Ensure support is available throughout an employee’s career

#6. Final Discussion & Conclusion

**Strengths of the Analysis:**

* This analysis provides a structured and comprehensive exploration of mental health in the workplace. Multiple visualization techniques were used effectively to uncover meaningful patterns. The insights are supported by clear visual evidence and aligned with business objectives.

**Limitations**
* The dataset is based on self-reported survey data, which may introduce bias
* Some variables contain missing or incomplete values
* The dataset is limited to specific industries and may not generalize to all workplaces

**Key Insights**

* Gender differences exist in treatment-seeking behavior
* Mental health impacts employees across all age groups
* Remote work shows mixed effects on mental health
* Company support strongly influences employee behavior
* Awareness of resources remains a challenge

**Business Implications**

These findings highlight the importance of proactive mental health strategies in the workplace. Organizations that invest in awareness, support systems, and inclusive policies are more likely to see improved employee well-being and productivity.

**Recommendations**

Based on these findings, I recommend the following actions for HR and leadership teams:

* Develop targeted mental health programs
* Increase awareness of available resources
* Foster a culture that reduces stigma
Provide flexible and accessible support systems

**Conclusion**

This analysis shows that data-driven approaches can provide valuable insights into employee mental health. Despite some limitations, the findings offer clear guidance for organizations to improve workplace well-being through targeted support, increased awareness, and inclusive policies.
"""